### ISSUE TITLE
Inefficient single-level object lookup.

### ISSUE THREAD

**Issue by amcgregor** [Pylons/virginia#1]
By using `__getitem__` the way the code currently does is severely restrictive of performance when looking up deeply nested files.  I would be honestly curious to see how this can be made more efficient.

**Comment by mcdonc** [comment]
Not sure what action to take on this bug report.  It's just an example app really, not really meant for any sort of high-performance fileserving (Apache, et. al. are always going to be the best choice for that).

If you mean that the idea of traversal is inherently slow, it all depends on what `__getitem__` does, really, but that discussion is probably better had on a list somewhere.

**Comment by amcgregor** [comment]
This project being an example app provides an excellent opportunity to display both the up-front, rapid development method (the simple `__getitem__` currently utilized) as well as demonstrate optimization techniques.

The optimization I'm currently thinking of is specifically the consumption of multiple path elements (for an app like this, _all_ of the path elements).  This is less of a bug report than it is a feature request.  ;)

Consider the following:

```
class Filesystem(Controller):
    base = "/some/path/"

    def __default__(self, *parts):
        # Like __getitem__, but consumes all path elements.

        path = os.path.normpath(os.path.join(self.base, *parts))

        if not path.startswith(base):
            raise HTTPForbidden("Cowardly refusing to violate base path policy.")

        if not os.path.exists(path):
            raise HTTPNotFound()

        if not os.path.isfile(path):
            raise HTTPForbidden("Cowardly refusing to open a non-file.")

        # Create a response and populate it.
        response = webob.Response()

        return response
```

The above is a simplification (omitting the gritty details which are mixed in with the dispatch) of the [Theme static file server](https://github.com/GothAlice/Contentment/blob/master/web/extras/contentment/components/theme/controller.py#L23-70) from [Contentment](http://www.web-core.org/contentment/).

I'm not trying to flame; I really do want to understand what the possibilities are for traversal, and I learn by example.  :(

**Comment by mcdonc** [comment]
The Pyramid traverser implementation is pluggable: http://docs.pylonsproject.org/projects/pyramid/1.0/narr/hooks.html#changing-the-traverser

An older example traverser from BFG that does (halfass) TG object dispatch style traversal is here as "Traverser": http://svn.repoze.org/repoze.bfg.metatg/trunk/repoze/bfg/metatg/__init__.py

**Comment by mcdonc** [comment]
An updated Pyramid variant named `pyramid_metatg` was just uploaded here: https://github.com/Pylons/pyramid_metatg
